export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_NOT_VISIBLE = 'SET_NOT_VISIBLE';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
export const SET_MORE_ENTITY_SHADOW = 'SET_MORE_ENTITY_SHADOW';
